myapp/urls.py
from django.urls import path
from .views import TaskDetailView, TaskUpdateView, CreateCumListView, create_user_profile, Style_test
from .views import LoginView, more_details
app_name = 'myapp'
urlpatterns = [
    path('', CreateCumListView.as_view(), name='task-list'),
    #path('', TaskListView.as_view(), name='task-list'),
    path('<int:pk>/', TaskDetailView.as_view(), name='task-detail'),
    #path('create', TaskCreateView.as_view(), name='task-create'),
    path('<int:pk>/update/', TaskUpdateView.as_view(), name='task-update'),
    #path('<int:pk>/delete/', TaskDeleteView.as_view(), name='task-delete'),
    path('style/', Style_test, name='style-test'),
    path('register/', create_user_profile, name='create_user_profile'),
    path('login/', LoginView.as_view(), name='login'),
    path('know/', more_details.as_view(), name='know')
]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include
import myapp

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls'))
]

myapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse_lazy

class Task(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=200, default='null')
    description = models.CharField(max_length=200, default='null')
    completed = models.BooleanField(default=False)
    #task_holder = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

class UserProfile(models.Model):
    #user = models.OneToOneField(User, on_delete=models.CASCADE)
    #user = models.OneToOneField(User, on_delete=models.CASCADE)
    # Add additional fields for the user profile here
    # For example:
    # An additional field added (boolen)
    marital_status = models.BooleanField(default=False)
    bio = models.TextField(max_length=500, blank=True)
    location = models.CharField(max_length=30, blank=True)
    birthdate = models.DateField(null=True, blank=True)
    '''
    def get_absolute_url(self):
        return reverse_lazy('', args=[str(self.id)])
    '''

    '''
    def __str__(self):
        return self.user.username
    '''

myapp/forms.py
from django import forms
from .models import Task, UserProfile #UserProfile
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['title', 'description', 'completed']

# shall use a generic one!
class UserProfileForm(UserCreationForm):

    class Meta:
        model = User
        fields = ['username']
    def save(self, commit=True):
        user = super(UserProfileForm, self).save(commit=False)
        if commit:
            user.save()
        return user

class UserDetailForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = "__all__"

'''
class TaskForm(forms.ModelForm):
    class meta:

        model = Task
        title = forms.CharField(label='Task Title', max_length=100)
        dsc = forms.CharField(label='Task Description', max_length=550)
        completed = forms.BooleanField(label='You didnt finish that. did you!', initial=True)
'''

myapp/views.py
from django.shortcuts import render, redirect
from django.shortcuts import reverse
from django.views.generic import ListView, DetailView, TemplateView, FormView
from django.views.generic.edit import CreateView, UpdateView
from .models import Task, UserProfile
from .forms import TaskForm, UserProfileForm, UserDetailForm
from django.views.generic.edit import DeleteView
from .forms import TaskForm
from django import forms
from django.views import View
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate, login
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.

def create_user_profile(request):
    if request.method == 'POST':
        form = UserProfileForm(request.POST)
        if form.is_valid():
            profile = form.save(commit=False)
            profile.user = request.user
            profile.save()
            return redirect('/know') #redirection... To login...
    else:
        form = UserProfileForm()
    return render(request, 'myapp/create_user_profile.html', {'form': form})

class more_details(CreateView):
    template_name = 'myapp/more.html'
    model = UserProfile
    form_class = UserDetailForm
    success_url = 'login/'
    
    def form_valid(self, form):
        detail = form.save(commit=False)
        detail.save()

        form.instance.owner = self.request.user
        inst = super().form_valid(form)
        return inst

class LoginView(View):
    form_class = AuthenticationForm
    template_name = 'myapp/login.html'

    def get(self, request):
        form = self.form_class()
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('/')
        return render(request, self.template_name, {'form': form})

def Style_test(request):
    return render(request, 'myapp/styling.html')

#form view
class MyFormView(FormView):
    template_name = 'myapp/mypage.html'
    form_class = TaskForm

# This one would bring all in one page (view inheritance)
# thats one way to do that
class CreateCumListView(CreateView, ListView, LoginRequiredMixin):
    template_name='myapp/mypage.html'
    form_class = TaskForm
    model = Task
    success_url = '/'

    def form_valid(self, form):
        form.instance.user = self.request.user
        if form.instance.user is not None:
            inst = super().form_valid(form)
            return inst

    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            # Add user-specific content to the context
            context['user_content'] = 'Hello, ' + self.request.user.username
        return context

class TaskDetailView(DetailView):
    model = Task
    template_name = 'myapp/task_detail.html'
    context_object_name = 'task'

class TaskUpdateView(UpdateView):
    model = Task
    form_class = TaskForm
    template_name = 'myapp/task_form.html'
    success_url = '/'

'''
class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['title', 'description', 'completed']

def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['object_list'] = self.get_queryset()
        return context

def post(self, request, *args, **kwargs):
        if 'delete' in request.POST:
            return self.delete(request, *args, **kwargs)
        else:    
            return super().post(request, *args, **kwargs)
    
def delete(self, request, *args, **kwargs):
        pk = kwargs['pk']
        self.get_object().delete()
        return self.get(request, *args, **kwargs)

class TaskDeleteView(DeleteView):
    model = Task
    template_name = 'myapp/mypage.html'
    success_url = reverse_lazy('myapp:task-list')        
'''

myapp/templates/myapp/base.html
<!doctype html>
<html lang="en">
    {%load static%}
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
</head>
  <body>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js" integrity="sha384-mQ93GR66B00ZXjt0YO5KlohRA5SY2XofN4zfuZxLkoj1gXtW8ANNCe9d5Y3eG5eD" crossorigin="anonymous"></script>
    
    <main>
        <header class="p-3 text-bg-dark">
            <div class="container">
              <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
                <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
                  <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"></use></svg>
                </a>
        
                <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                  <li><a href="#" class="nav-link px-2 text-secondary">Home</a></li>
                  <li><a href="#" class="nav-link px-2 text-white">Features</a></li>
                  <li><a href="#" class="nav-link px-2 text-white">Pricing</a></li>
                  <li><a href="#" class="nav-link px-2 text-white">FAQs</a></li>
                  <li><a href="#" class="nav-link px-2 text-white">About</a></li>
                </ul>
        
                <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" role="search">
                  <input type="search" class="form-control form-control-dark text-bg-dark" placeholder="Search..." aria-label="Search">
                </form>
        
                <div class="text-end">
                  <button type="button" class="btn btn-outline-light me-2">Login</button>
                  <a href="register/">
                    <button type="button" class="btn btn-warning" >Sign-up</button>
                  </a>
                </div>
              </div>
            </div>
          </header>
            <div class="list-group w-auto">
            {% block task_list %}
            
            {%endblock%}
            </div>
        </main>
    </body>
</html>

myapp/templates/myapp/create_user_profile.html
<!DOCTYPE html>
<html>
    <body>
        yup! thats registeration page...
        <div id="form-div" >
            <form method="post" class="create-form">
                {% csrf_token%}
                {{form.as_p}}
                <input type="submit">
            </form>
    </body>
</html>

myapp/templates/myapp/login.html
<!DOCTYPE html>
<html>
    <Body>
         <h2>Login</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Login</button>
    </form>
    </Body>
</html>
   

myapp/templates/myapp/more.html
<!DOCTYPE html>
<html>
    <Body>
         <h2>Login</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Login</button>
    </form>
    </Body>
</html>

myapp/templates/myapp/mypage.html
{%extends "myapp/base.html"%}

{%load static%}

<h2>list of created tasks</h2>

{% block task_list%}


<div id="dashboard" style="border: 3px; border-color: black; position: absolute; right: 45px;">
    
        {% if user_content %}
     <p>{{ user_content }}</p>
{% endif %}
    
</div>

<div id="task-div" style="width: 50%; height: 500px; padding-top: 25px; padding-right: 25px;">
    <ul>
        <label class="list-group-item d-flex gap-3">
            <span class="pt-1 form-checked-content">
              <strong>Create here! </strong>
              {%comment%}<small class="d-block text-muted">
                <svg class="bi me-1" width="1em" height="1em"><use xlink:href="#calendar-event"></use></svg>
                small text here
              </small>
              {%endcomment%}
              <div id="form-div" >
                <form method="post" class="create-form">
                    {% csrf_token%}
                    {{form.as_p}}
                    <input type="submit">
                </form>
                </div>
            </span>
          </label>

          {% if object_list %}
    {% for task in object_list %}
    <label class="list-group-item d-flex gap-3">
        <input class="form-check-input flex-shrink-0" type="checkbox" value="" checked="task.completed" style="font-size: 1.375em;">
        <span class="pt-1 form-checked-content">
          <strong><a href="{% url 'myapp:task-detail' task.pk %}">{{ task.title }}</a> - {{ task.description }}</strong>
          
        </span>
      </label>
      {% endfor %}
  </ul>
</div>
{% else %}
  <p>No instances found.</p>
{% endif %}

{% endblock  %}
{% block styles %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
{% endblock %}

myapp/templates/myapp/popup.html
{% extends 'base.html' %}

{% block content %}
    <h1>Popup window</h1>
    <p>This is the content that will be displayed in the pop-up window.</p>
{% endblock %}

{% block javascript %}
    <script>
        // Code to display the pop-up window

</script>
{% endblock %}

myapp/templates/myapp/styling.html
<!doctype html>
<html lang="en">
    {%block styles%} {%endblock%}
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
  </head>
  <body>
    <div id="test_btn" style="height: 30px; width: 45 px;">
    <button type="button" class="btn btn-sm btn-primary  w-10 mx-0 mb-2">Save changes</button>
    </div>
</body>
</html>

myapp/templates/myapp/task_detail.html
<h1>{{task.title}}</h1>
<h2>{{task.description}}</h2>
<h3> {{task.completed}} </h3>

myapp/templates/myapp/task_form.html
create the task here!
<form method="post">
    {% csrf_token%}
    {{form.as_p}}
    <input type="submit">
</form>

myapp/templates/myapp/task_list.html
{% block content %}
    <h1>Task List</h1>
    <ul>
        {% for task in tasks %}
            <li><a href="{% url 'myapp:task-detail' task.pk %}">{{ task.title }}</a></li>
        {% empty %}
            <li>No tasks yet.</li>
        {% endfor %}
    </ul>
    <a href="{% url 'myapp:task-create' %}">Create a new task</a>
{% endblock %}